name: CI

on:
  push:
    branches:
      - "**"
    workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
    outputs:
      GitVersion_MajorMinorPatch: ${{ steps.version.outputs.GitVersion_MajorMinorPatch }}

  test:
    runs-on: ubuntu-20.04
    container: maven:3-eclipse-temurin-21
    needs: version
    env:
      REVISION: ${{ needs.version.outputs.GitVersion_MajorMinorPatch }}

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: mvn test -ntp -Drevision=$REVISION

  build:
    runs-on: ubuntu-20.04
    container: maven:3-eclipse-temurin-21
    needs: [version, test]
    env:
      REVISION: ${{ needs.version.outputs.GitVersion_MajorMinorPatch }}

    steps:
      - uses: actions/checkout@v4

      - name: Build binaries
        run: mvn package -ntp -Drevision=$REVISION

  tagging:
    runs-on: ubuntu-20.04
    needs: [version, test, build]
    env:
      REVISION: ${{ needs.version.outputs.GitVersion_MajorMinorPatch }}
    steps:
      - uses: actions/checkout@v4

      - name: Push tag to the repo
        run: |
          git tag $REVISION
          git push --tags